import sys
import json
import os

TEMPLATES = {
    "ions": {
        "integrator": "steep",
        "nsteps": "0",
        "emtol": "1000.0",
        "emstep": "0.01",
        "cutoff-scheme": "Verlet",
        "nstlist": "1",
        "coulombtype": "PME",
        "rcoulomb": "1.0",
        "rvdw": "1.0",
        "pbc": "xyz"
    },
    "minim": {
        "integrator": "steep",
        "emtol": "1000.0",
        "emstep": "0.01",
        "nsteps": "50000",
        "nstlist": "1",
        "cutoff-scheme": "Verlet",
        "coulombtype": "PME",
        "rcoulomb": "1.0",
        "rvdw": "1.0",
        "pbc": "xyz"
    },
    "nvt": {
        "integrator": "md",
        "nsteps": "50000",
        "dt": "0.001",
        "nstxout": "500",
        "nstvout": "500",
        "nstenergy": "500",
        "nstlog": "500",
        "cutoff-scheme": "Verlet",
        "nstlist": "10",
        "rcoulomb": "1.0",
        "rvdw": "1.0",
        "coulombtype": "PME",
        "tcoupl": "V-rescale",
        "tc-grps": "Protein Non-Protein",
        "tau_t": "0.1  0.1",
        "ref_t": "300  300",
        "pcoupl": "no",
        "define": "-DPOSRES",
        "constraints": "h-bonds",
        "constraint_algorithm": "lincs",
        "continuation": "no",
        "gen_vel": "yes",
        "gen_temp": "300",
        "gen_seed": "-1"
    },
    "npt": {
        "integrator": "md",
        "nsteps": "50000",
        "dt": "0.001",
        "nstxout": "500",
        "nstvout": "500",
        "nstenergy": "500",
        "nstlog": "500",
        "cutoff-scheme": "Verlet",
        "nstlist": "10",
        "rcoulomb": "1.0",
        "rvdw": "1.0",
        "coulombtype": "PME",
        "tcoupl": "V-rescale",
        "tc-grps": "Protein Non-Protein",
        "tau_t": "0.1  0.1",
        "ref_t": "300  300",
        "pcoupl": "Parrinello-Rahman",
        "pcoupltype": "isotropic",
        "tau_p": "2.0",
        "ref_p": "1.0",
        "compressibility": "4.5e-5",
        "define": "-DPOSRES",
        "constraints": "h-bonds",
        "constraint_algorithm": "lincs",
        "continuation": "yes",
        "gen_vel": "no"
    },
    "md": {
        "integrator": "md",
        "nsteps": "5000000",
        "dt": "0.001",
        "nstxout": "0",
        "nstvout": "0",
        "nstfout": "0",
        "nstxout-compressed": "5000",
        "nstenergy": "5000",
        "nstlog": "5000",
        "cutoff-scheme": "Verlet",
        "nstlist": "10",
        "rcoulomb": "1.0",
        "rvdw": "1.0",
        "coulombtype": "PME",
        "tcoupl": "V-rescale",
        "tc-grps": "Protein Non-Protein",
        "tau_t": "0.1  0.1",
        "ref_t": "300  300",
        "pcoupl": "Parrinello-Rahman",
        "pcoupltype": "isotropic",
        "tau_p": "2.0",
        "ref_p": "1.0",
        "compressibility": "4.5e-5",
        "define": "",
        "constraints": "h-bonds",
        "constraint_algorithm": "lincs",
        "continuation": "yes",
        "gen_vel": "no"
    }
}

MDP_WHITELIST = {
    "integrator", "nsteps", "dt", "emtol", "emstep", "nstxout", "nstvout", "nstfout",
    "nstenergy", "nstlog", "nstxout-compressed", "nstlist", "cutoff-scheme",
    "ns_type", "coulombtype", "rcoulomb", "rvdw", "pbc", "tcoupl", "tc-grps",
    "tau_t", "ref_t", "pcoupl", "pcoupltype", "tau_p", "ref_p", "compressibility",
    "refcoord_scaling", "gen_vel", "gen_temp", "gen_seed", "define", "constraints",
    "constraint_algorithm", "continuation"
}

def compose_mdp(input_data):
    phase = input_data.get("phase")
    overrides = input_data.get("overrides", {})
    cwd = input_data.get("cwd", os.getcwd())
    
    if phase not in TEMPLATES:
        return {"status": "error", "message": f"Unknown phase: {phase}"}
    
    # Whitelist validation
    invalid_keys = [k for k in overrides if k not in MDP_WHITELIST]
    if invalid_keys:
        return {
            "status": "error", 
            "message": f"Invalid MDP parameter(s): {', '.join(invalid_keys)}",
            "whitelist": sorted(list(MDP_WHITELIST))
        }
        
    params = TEMPLATES[phase].copy()
    params.update(overrides)
    
    if not os.path.exists(cwd):
        os.makedirs(cwd, exist_ok=True)
    
    output_file = f"{phase}.mdp"
    output_path = os.path.join(cwd, output_file)
    
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"; {phase} MDP automatically generated by MdpComposer\n")
            for k, v in params.items():
                f.write(f"{k.ljust(20)} = {v}\n")
                
        return {
            "status": "success",
            "output_file": output_file,
            "final_params": params
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1].startswith("{"):
            input_data = json.loads(sys.argv[1])
        else:
            with open(sys.argv[1], "r") as f:
                input_data = json.load(f)
    else:
        input_data = json.loads(sys.stdin.read())
        
    result = compose_mdp(input_data)
    print(json.dumps(result, indent=2, ensure_ascii=False))
