"""The `define` mdp key.

render() ends in template.format(**params), which silently drops keys that have
no placeholder. Before this change, passing define= was accepted and discarded,
so an EM meant to run under -DSTRONG_POSRES ran unrestrained instead. Both
tutorials also call for -DPOSRES during equilibration, which never reached any
rendered mdp.
"""
import re
from pathlib import Path

import pytest

from lib.mdp_templates import base as MDP


def _define(path):
    m = re.search(r"^define[ \t]*=[ \t]*(.*)$", path.read_text(), re.M)
    return None if m is None else m.group(1).split(";")[0].strip()


def test_equilibration_phases_restrain_the_protein_by_default(tmp_path):
    """posre.itp is generated by pdb2gmx; -DPOSRES is what activates it."""
    for phase in ("nvt", "npt"):
        out = MDP.render(phase, {}, tmp_path)
        assert _define(out) == "-DPOSRES", phase


def test_em_has_no_define_by_default(tmp_path):
    assert _define(MDP.render("em", {}, tmp_path)) == ""


def test_override_reaches_the_rendered_file(tmp_path):
    out = MDP.render("em", {"define": "-DSTRONG_POSRES"}, tmp_path)
    assert _define(out) == "-DSTRONG_POSRES"


def test_multiple_defines_survive(tmp_path):
    out = MDP.render("npt", {"define": "-DPOSRES -DPOSRES_LIPID"}, tmp_path)
    assert _define(out) == "-DPOSRES -DPOSRES_LIPID"


@pytest.mark.parametrize("phase", ["em", "nvt", "npt"])
def test_define_line_exists_in_every_touched_template(phase, tmp_path):
    """A missing placeholder is silent, so assert the line is present at all."""
    assert _define(MDP.render(phase, {}, tmp_path)) is not None


@pytest.mark.integration
def test_grompp_accepts_a_restrained_nvt_and_rejects_it_without_r(tmp_path):
    """The regression guard for -DPOSRES: grompp needs -r since GROMACS 2018.

    Builds its own inputs from tracked tutorial data. It must not read `runs/`,
    which is gitignored and therefore absent from a fresh clone or worktree --
    a test that always skips guards nothing.

    tc_grps is forced to System via has_protein=False: the box holds an
    unsolvated protein, so the default "Protein Non-Protein" would fail on the
    missing Non-Protein group for reasons unrelated to restraints.
    """
    import os
    import shutil
    import subprocess

    gmx = shutil.which("gmx")
    if gmx is None:
        pytest.skip("gmx not on PATH")
    pdb = Path("tutorial_data/Lysozyme_in_water/1AKI.pdb")
    if not pdb.is_file():
        pytest.skip("needs tutorial_data/Lysozyme_in_water/1AKI.pdb")

    env = {**os.environ, "GMX_MAXBACKUP": "-1"}
    # Crystal waters confuse pdb2gmx with this force field; drop them.
    (tmp_path / "clean.pdb").write_text(
        "".join(l for l in pdb.read_text().splitlines(keepends=True)
                if "HOH" not in l)
    )
    subprocess.run(
        [gmx, "pdb2gmx", "-f", "clean.pdb", "-o", "p.gro", "-p", "topol.top",
         "-water", "spc", "-ff", "charmm36", "-ignh"],
        cwd=tmp_path, capture_output=True, text=True, env=env, check=True,
    )
    assert (tmp_path / "posre.itp").is_file(), "pdb2gmx wrote no restraint file"
    subprocess.run(
        [gmx, "editconf", "-f", "p.gro", "-o", "box.gro", "-c", "-d", "1.5",
         "-bt", "cubic"],
        cwd=tmp_path, capture_output=True, text=True, env=env, check=True,
    )

    mdp = MDP.render("nvt", {"nsteps": 10, "has_protein": False}, tmp_path)
    assert "-DPOSRES" in _define(mdp)

    def grompp(*extra, out):
        return subprocess.run(
            [gmx, "grompp", "-f", mdp.name, "-c", "box.gro", *extra,
             "-p", "topol.top", "-o", out, "-maxwarn", "2"],
            cwd=tmp_path, capture_output=True, text=True, env=env,
        )

    with_r = grompp("-r", "box.gro", out="nvt.tpr")
    assert with_r.returncode == 0, with_r.stderr[-2000:]
    assert (tmp_path / "nvt.tpr").is_file()

    # Without -r the same mdp must fail, or this test proves nothing.
    without_r = grompp(out="no_r.tpr")
    assert without_r.returncode != 0
    assert "option -r" in without_r.stderr


@pytest.mark.integration
def test_every_phase_renders_without_a_key_error(tmp_path):
    """npt_pr renders from npt.mdp, so a placeholder there needs a default."""
    from lib.mdp_templates import base as _base
    for phase in sorted(_base._FILES):
        MDP.render(phase, {}, tmp_path)


def test_run_phase_passes_the_restraint_reference(run_phase_grompp_args):
    """Guard the wiring, not just GROMACS's behaviour.

    The integration test above proves that -DPOSRES needs -r, but it calls
    grompp directly with its own -r, so deleting the wiring in run_phase leaves
    it green. This inspects the argument list run_phase actually builds.
    """
    # nvt defaults to define = -DPOSRES, so -r is required and must point at
    # the phase's own input coordinates.
    _, args = run_phase_grompp_args("restrained", "nvt", stage2_files=["em.gro"])
    assert args[args.index("-r") + 1] == args[args.index("-c") + 1]
    assert args[args.index("-c") + 1].endswith("stage2_md/em.gro")

    # em has no restraints; -r there would demand a file nothing produces.
    _, args = run_phase_grompp_args("free", "em")
    assert "-r" not in args


@pytest.mark.parametrize("define,expected", [
    ("-DPOSRES", True),
    ("-DPOSRES -DPOSRES_LIPID", True),
    ("-DSTRONG_POSRES", False),
    ("", False),
])
def test_mdp_defines_restraints_detects_posres(tmp_path, define, expected):
    """-DSTRONG_POSRES guards a different include and is handled by the
    assembly, which passes its own -r; only -DPOSRES drives this branch."""
    from skills.md_runner import md_runner as MD
    mdp = tmp_path / "phase.mdp"
    mdp.write_text(f"define                   = {define}\nintegrator = md\n")
    assert MD._mdp_defines_restraints(mdp) is expected
