"""The `define` mdp key.

render() ends in template.format(**params), which silently drops keys that have
no placeholder. Before this change, passing define= was accepted and discarded,
so an EM meant to run under -DSTRONG_POSRES ran unrestrained instead. Both
tutorials also call for -DPOSRES during equilibration, which never reached any
rendered mdp.
"""
import re

import pytest

from lib.mdp_templates import base as MDP


def _define(path):
    m = re.search(r"^define\s*=\s*(.*)$", path.read_text(), re.M)
    return None if m is None else m.group(1).split(";")[0].strip()


def test_equilibration_phases_restrain_the_protein_by_default(tmp_path):
    """posre.itp is generated by pdb2gmx; -DPOSRES is what activates it."""
    for phase in ("nvt", "npt"):
        out = MDP.render(phase, {}, tmp_path)
        assert _define(out) == "-DPOSRES", phase


def test_em_has_no_define_by_default(tmp_path):
    assert _define(MDP.render("em", {}, tmp_path)) == ""


def test_override_reaches_the_rendered_file(tmp_path):
    out = MDP.render("em", {"define": "-DSTRONG_POSRES"}, tmp_path)
    assert _define(out) == "-DSTRONG_POSRES"


def test_multiple_defines_survive(tmp_path):
    out = MDP.render("npt", {"define": "-DPOSRES -DPOSRES_LIPID"}, tmp_path)
    assert _define(out) == "-DPOSRES -DPOSRES_LIPID"


@pytest.mark.parametrize("phase", ["em", "nvt", "npt"])
def test_define_line_exists_in_every_touched_template(phase, tmp_path):
    """A missing placeholder is silent, so assert the line is present at all."""
    assert _define(MDP.render(phase, {}, tmp_path)) is not None
